// flow-typed signature: a2fb4ee64acca460ddd23f8700b8009f
// flow-typed version: <<STUB>>/react-native-calendars_v^1.17.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-calendars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-calendars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-calendars/spec/runner' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/agenda/index' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/agenda/platform-style.ios' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/agenda/platform-style' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/agenda/reservation-list/index' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/agenda/reservation-list/reservation' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/agenda/reservation-list/style' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/agenda/style' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar-list/index' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar-list/item' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar-list/style' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar/day/basic/index' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar/day/basic/style' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar/day/multi-dot/index' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar/day/multi-dot/style' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar/day/period/index' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar/day/period/style' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar/header/index' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar/header/style' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar/index' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar/style' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/calendar/updater' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/dateutils' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/index' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/input' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/interface' {
  declare module.exports: any;
}

declare module 'react-native-calendars/src/style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-calendars/spec/runner.js' {
  declare module.exports: $Exports<'react-native-calendars/spec/runner'>;
}
declare module 'react-native-calendars/src/agenda/index.js' {
  declare module.exports: $Exports<'react-native-calendars/src/agenda/index'>;
}
declare module 'react-native-calendars/src/agenda/platform-style.ios.js' {
  declare module.exports: $Exports<'react-native-calendars/src/agenda/platform-style.ios'>;
}
declare module 'react-native-calendars/src/agenda/platform-style.js' {
  declare module.exports: $Exports<'react-native-calendars/src/agenda/platform-style'>;
}
declare module 'react-native-calendars/src/agenda/reservation-list/index.js' {
  declare module.exports: $Exports<'react-native-calendars/src/agenda/reservation-list/index'>;
}
declare module 'react-native-calendars/src/agenda/reservation-list/reservation.js' {
  declare module.exports: $Exports<'react-native-calendars/src/agenda/reservation-list/reservation'>;
}
declare module 'react-native-calendars/src/agenda/reservation-list/style.js' {
  declare module.exports: $Exports<'react-native-calendars/src/agenda/reservation-list/style'>;
}
declare module 'react-native-calendars/src/agenda/style.js' {
  declare module.exports: $Exports<'react-native-calendars/src/agenda/style'>;
}
declare module 'react-native-calendars/src/calendar-list/index.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar-list/index'>;
}
declare module 'react-native-calendars/src/calendar-list/item.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar-list/item'>;
}
declare module 'react-native-calendars/src/calendar-list/style.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar-list/style'>;
}
declare module 'react-native-calendars/src/calendar/day/basic/index.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar/day/basic/index'>;
}
declare module 'react-native-calendars/src/calendar/day/basic/style.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar/day/basic/style'>;
}
declare module 'react-native-calendars/src/calendar/day/multi-dot/index.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar/day/multi-dot/index'>;
}
declare module 'react-native-calendars/src/calendar/day/multi-dot/style.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar/day/multi-dot/style'>;
}
declare module 'react-native-calendars/src/calendar/day/period/index.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar/day/period/index'>;
}
declare module 'react-native-calendars/src/calendar/day/period/style.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar/day/period/style'>;
}
declare module 'react-native-calendars/src/calendar/header/index.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar/header/index'>;
}
declare module 'react-native-calendars/src/calendar/header/style.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar/header/style'>;
}
declare module 'react-native-calendars/src/calendar/index.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar/index'>;
}
declare module 'react-native-calendars/src/calendar/style.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar/style'>;
}
declare module 'react-native-calendars/src/calendar/updater.js' {
  declare module.exports: $Exports<'react-native-calendars/src/calendar/updater'>;
}
declare module 'react-native-calendars/src/dateutils.js' {
  declare module.exports: $Exports<'react-native-calendars/src/dateutils'>;
}
declare module 'react-native-calendars/src/index.js' {
  declare module.exports: $Exports<'react-native-calendars/src/index'>;
}
declare module 'react-native-calendars/src/input.js' {
  declare module.exports: $Exports<'react-native-calendars/src/input'>;
}
declare module 'react-native-calendars/src/interface.js' {
  declare module.exports: $Exports<'react-native-calendars/src/interface'>;
}
declare module 'react-native-calendars/src/style.js' {
  declare module.exports: $Exports<'react-native-calendars/src/style'>;
}
