// flow-typed signature: bb3c1535a9d97685951df5e18ee2403f
// flow-typed version: <<STUB>>/victory-native_v^0.17.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'victory-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'victory-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'victory-native/lib/components/victory-area' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-axis' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-bar' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-brush-container' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-candlestick' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-chart' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-clip-container' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-container' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-cursor-container' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-errorbar' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-group' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-label' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-legend' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-line' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-pie' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-polar-axis' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-portal/portal' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-portal/victory-portal' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/arc' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/area' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/axis' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/bar' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/border' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/candle' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/circle' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/clip-path' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/curve' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/error-bar' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/flyout' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/line' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/path' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/point' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/rect' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/slice' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/text' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/tspan' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-primitives/voronoi' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-scatter' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-selection-container' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-stack' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-tooltip' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-voronoi-container' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-voronoi' {
  declare module.exports: any;
}

declare module 'victory-native/lib/components/victory-zoom-container' {
  declare module.exports: any;
}

declare module 'victory-native/lib/helpers/create-container' {
  declare module.exports: any;
}

declare module 'victory-native/lib/helpers/native-helpers' {
  declare module.exports: any;
}

declare module 'victory-native/lib/helpers/native-zoom-helpers' {
  declare module.exports: any;
}

declare module 'victory-native/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'victory-native/lib/components/victory-area.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-area'>;
}
declare module 'victory-native/lib/components/victory-axis.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-axis'>;
}
declare module 'victory-native/lib/components/victory-bar.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-bar'>;
}
declare module 'victory-native/lib/components/victory-brush-container.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-brush-container'>;
}
declare module 'victory-native/lib/components/victory-candlestick.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-candlestick'>;
}
declare module 'victory-native/lib/components/victory-chart.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-chart'>;
}
declare module 'victory-native/lib/components/victory-clip-container.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-clip-container'>;
}
declare module 'victory-native/lib/components/victory-container.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-container'>;
}
declare module 'victory-native/lib/components/victory-cursor-container.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-cursor-container'>;
}
declare module 'victory-native/lib/components/victory-errorbar.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-errorbar'>;
}
declare module 'victory-native/lib/components/victory-group.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-group'>;
}
declare module 'victory-native/lib/components/victory-label.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-label'>;
}
declare module 'victory-native/lib/components/victory-legend.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-legend'>;
}
declare module 'victory-native/lib/components/victory-line.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-line'>;
}
declare module 'victory-native/lib/components/victory-pie.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-pie'>;
}
declare module 'victory-native/lib/components/victory-polar-axis.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-polar-axis'>;
}
declare module 'victory-native/lib/components/victory-portal/portal.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-portal/portal'>;
}
declare module 'victory-native/lib/components/victory-portal/victory-portal.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-portal/victory-portal'>;
}
declare module 'victory-native/lib/components/victory-primitives/arc.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/arc'>;
}
declare module 'victory-native/lib/components/victory-primitives/area.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/area'>;
}
declare module 'victory-native/lib/components/victory-primitives/axis.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/axis'>;
}
declare module 'victory-native/lib/components/victory-primitives/bar.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/bar'>;
}
declare module 'victory-native/lib/components/victory-primitives/border.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/border'>;
}
declare module 'victory-native/lib/components/victory-primitives/candle.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/candle'>;
}
declare module 'victory-native/lib/components/victory-primitives/circle.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/circle'>;
}
declare module 'victory-native/lib/components/victory-primitives/clip-path.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/clip-path'>;
}
declare module 'victory-native/lib/components/victory-primitives/curve.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/curve'>;
}
declare module 'victory-native/lib/components/victory-primitives/error-bar.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/error-bar'>;
}
declare module 'victory-native/lib/components/victory-primitives/flyout.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/flyout'>;
}
declare module 'victory-native/lib/components/victory-primitives/line.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/line'>;
}
declare module 'victory-native/lib/components/victory-primitives/path.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/path'>;
}
declare module 'victory-native/lib/components/victory-primitives/point.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/point'>;
}
declare module 'victory-native/lib/components/victory-primitives/rect.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/rect'>;
}
declare module 'victory-native/lib/components/victory-primitives/slice.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/slice'>;
}
declare module 'victory-native/lib/components/victory-primitives/text.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/text'>;
}
declare module 'victory-native/lib/components/victory-primitives/tspan.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/tspan'>;
}
declare module 'victory-native/lib/components/victory-primitives/voronoi.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-primitives/voronoi'>;
}
declare module 'victory-native/lib/components/victory-scatter.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-scatter'>;
}
declare module 'victory-native/lib/components/victory-selection-container.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-selection-container'>;
}
declare module 'victory-native/lib/components/victory-stack.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-stack'>;
}
declare module 'victory-native/lib/components/victory-tooltip.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-tooltip'>;
}
declare module 'victory-native/lib/components/victory-voronoi-container.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-voronoi-container'>;
}
declare module 'victory-native/lib/components/victory-voronoi.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-voronoi'>;
}
declare module 'victory-native/lib/components/victory-zoom-container.js' {
  declare module.exports: $Exports<'victory-native/lib/components/victory-zoom-container'>;
}
declare module 'victory-native/lib/helpers/create-container.js' {
  declare module.exports: $Exports<'victory-native/lib/helpers/create-container'>;
}
declare module 'victory-native/lib/helpers/native-helpers.js' {
  declare module.exports: $Exports<'victory-native/lib/helpers/native-helpers'>;
}
declare module 'victory-native/lib/helpers/native-zoom-helpers.js' {
  declare module.exports: $Exports<'victory-native/lib/helpers/native-zoom-helpers'>;
}
declare module 'victory-native/lib/index.js' {
  declare module.exports: $Exports<'victory-native/lib/index'>;
}
